"""
FFmpeg rendering engine for the viral hook clip.

Responsibilities:
  1. Trim the source video to [hook_start, hook_end].
  2. Reframe from horizontal (16:9) to vertical (9:16) via smart crop.
  3. Burn the .ass subtitle file directly into the video stream.

All three steps are executed in a SINGLE FFmpeg pass to avoid re-encoding
the video multiple times (which degrades quality and wastes CPU time).

Why subprocess over a Python FFmpeg wrapper library?
  - FFmpeg's filter_complex syntax is expressive but brittle when wrapped by
    third-party libraries. Using subprocess with an explicit argument list gives
    full control over every flag and avoids hidden incompatibilities between
    library versions and the locally installed FFmpeg binary.
"""

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path

from functools import lru_cache

logger = logging.getLogger(__name__)

# ── Output video settings ─────────────────────────────────────────────────────
OUTPUT_WIDTH = 1080
OUTPUT_HEIGHT = 1920

CRF = 20
AUDIO_CODEC = "aac"
AUDIO_BITRATE = "192k"


@lru_cache
def _get_available_video_encoder() -> tuple[str, list[str]]:
    """
    Detects the best available H.264 encoder in FFmpeg.
    Returns (encoder_name, extra_encoder_flags).
    """
    try:
        res = subprocess.run(["ffmpeg", "-encoders"], capture_output=True, text=True)
        out = res.stdout
        if "libx264" in out:
            return "libx264", ["-crf", str(CRF), "-preset", "fast"]
        if "libopenh264" in out:
            return "libopenh264", []
        if "h264_nvenc" in out:
            return "h264_nvenc", ["-preset", "p4"]
        if "h264_vaapi" in out:
            return "h264_vaapi", []
    except Exception:
        pass
    return "libx264", ["-crf", str(CRF), "-preset", "fast"]


@dataclass(frozen=True)
class RenderResult:
    output_path: Path
    duration_seconds: float


def render_clip(
    source_video: Path,
    subtitle_file: Path,
    hook_start: float,
    hook_end: float,
    output_path: Path,
) -> RenderResult:
    """
    Execute the full render pipeline in one FFmpeg call.

    Args:
        source_video:   Path to the original downloaded .mp4 file.
        subtitle_file:  Path to the .ass subtitle file generated by subtitle_generator.
        hook_start:     Start time of the hook in the source video (seconds).
        hook_end:       End time of the hook in the source video (seconds).
        output_path:    Destination path for the rendered final_clip.mp4.

    Returns:
        RenderResult with the output path and duration.

    Raises:
        RuntimeError: If FFmpeg exits with a non-zero return code.
        FileNotFoundError: If source_video does not exist.
    """
    if not source_video.exists():
        raise FileNotFoundError(f"Source video not found: {source_video}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    hook_duration = hook_end - hook_start

    # ── FFmpeg filter_complex explanation ─────────────────────────────────────
    #
    # We build a single filter_complex string with two chained filters:
    #
    # [0:v] crop=ih*(9/16):ih:(iw-ih*(9/16))/2:0 [cropped]
    #   - Takes input video stream [0:v]
    #   - crop=W:H:X:Y
    #       W = target width  = input_height * (9/16)   → preserves 9:16 ratio
    #       H = target height = input_height             → full height
    #       X = horizontal offset = center the crop horizontally
    #       Y = 0 (top-aligned)
    #   - Outputs as [cropped]
    #
    # [cropped] scale=1080:1920 [scaled]
    #   - Scales the cropped stream to exactly 1080x1920.
    #   - Handles edge cases where the source isn't exactly 1920px tall.
    #
    # [scaled] ass='...' [out]
    #   - Burns the .ass subtitle file into the scaled video stream.
    #   - The path must use forward slashes even on Windows for FFmpeg.

    ass_path = str(subtitle_file).replace("\\", "/")

    filter_complex = (
        f"[0:v]crop=ih*(9/16):ih:(iw-ih*(9/16))/2:0[cropped];"
        f"[cropped]scale={OUTPUT_WIDTH}:{OUTPUT_HEIGHT}[scaled];"
        f"[scaled]ass='{ass_path}'[out]"
    )

    encoder, encoder_flags = _get_available_video_encoder()

    cmd = [
        "ffmpeg",
        "-y",                           # overwrite output without asking
        "-ss", str(hook_start),         # seek BEFORE input (fast seek, not accurate to frame)
        "-i", str(source_video),        # input file
        "-t", str(hook_duration),       # duration to encode (not end time)
        "-filter_complex", filter_complex,
        "-map", "[out]",                # use the processed video stream
        "-map", "0:a",                  # use the original audio stream
        "-c:v", encoder,
        *encoder_flags,
        "-c:a", AUDIO_CODEC,
        "-b:a", AUDIO_BITRATE,
        "-movflags", "+faststart",      # move MP4 metadata to front for streaming
        str(output_path),
    ]

    logger.info(
        "Starting FFmpeg render for hook [%.2fs – %.2fs] → %s",
        hook_start,
        hook_end,
        output_path,
    )
    logger.debug("FFmpeg command: %s", " ".join(cmd))

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        logger.error("FFmpeg stderr:\n%s", result.stderr)
        raise RuntimeError(
            f"FFmpeg failed with exit code {result.returncode}.\n"
            f"stderr: {result.stderr[-2000:]}"   # last 2000 chars to avoid huge logs
        )

    logger.info(
        "Render complete: %s (%.1fs clip)",
        output_path,
        hook_duration,
    )

    return RenderResult(
        output_path=output_path,
        duration_seconds=hook_duration,
    )
